import requests
import datetime
import matplotlib.pyplot as plt

USERNAME = "muralimanas30"
REPO = "DSA-LEETCODE"
API_URL = f"https://leetcode-stats-api.herokuapp.com/{USERNAME}"
PIE_URL = f"https://raw.githubusercontent.com/{USERNAME}/{REPO}/main/leetcode_stats.png"
VIEW_BADGE = (
  "https://views-counter.vercel.app/badge"
  f"?pageId={USERNAME}%2F{REPO}&leftColor=000000&rightColor=0adb3f&type=total&label=Viewers&style=none"
)
FANCY_CARD_URL = (
  "https://fancy-readme-stats.vercel.app/api?"
  f"username={USERNAME}"
  "&theme=beach"
  "&show_icons=true"
  "&title=DSA+Journey"
  "&description=LeetCode+&+GitHub"
)

def fetch_stats():
    try:
        resp = requests.get(API_URL, timeout=10)
        return resp.json() if resp.status_code == 200 else {}
    except:
        return {}

def progress_bar(solved, total=3000, length=30):
    done = int(length * solved / total)
    return "[" + "█"*done + "▒"*(length-done) + f"] {solved}/{total}"

def generate_pie(e, m, h):
    labels = ["Easy", "Medium", "Hard"]
    values = [e, m, h]
    colors = ["#4CAF50", "#FFC107", "#F44336"]
    plt.figure(figsize=(4, 4))
    plt.pie(values, labels=labels, autopct="%1.1f%%", colors=colors, startangle=140)
    plt.title("Solved Distribution")
    plt.savefig("leetcode_stats.png", bbox_inches="tight")
    plt.close()

def main():
    data = fetch_stats()
    solved = data.get("totalSolved", 0)
    easy = data.get("easySolved", 0)
    medium = data.get("mediumSolved", 0)
    hard = data.get("hardSolved", 0)
    rank = data.get("ranking", "N/A")
    bar = progress_bar(solved)

    generate_pie(easy, medium, hard)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    readme = f"""# 📘 DSA-LEETCODE Dashboard

<p align="center">
  <img src="{VIEW_BADGE}" alt="Viewers Counter" />
</p>

<p align="center">
  <img src="{FANCY_CARD_URL}" alt="Fancy Stats Card" />
</p>

---

##  LeetCode Overview

- **Solved**: {solved} (Easy {easy}, Medium {medium}, Hard {hard})  
- **Global Rank**: {rank}  






{bar}


<p align="center">
  <img src="{PIE_URL}" alt="Difficulty Distribution" width="300"/>
</p>

---

##  Activity & Streaks

<p align="center">
  <img src="https://streak-stats.demolab.com/?user={USERNAME}&theme=tokyonight&hide_border=true" alt="Streak" />
</p>
<p align="center">
  <img src="https://github-readme-activity-graph.vercel.app/graph?username={USERNAME}&theme=tokyo-night&hide_border=true" alt="Activity Graph" />
</p>

---

##  Dev Thoughts

<p align="center">
  <img src="https://readme-typing-svg.herokuapp.com?size=22&duration=4000&color=36BCF7&center=true&width=700&lines=Code.+Debug.+Repeat.;Keep+learning;+keep+improving.;DSA+is+superpower.;Consistency+beats+results." alt="Typing Quote" />
</p>

---

*Generated by GitHub Workflows on {now}*
"""

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme)

if __name__ == "__main__":
    main()
