import requests
import datetime
import matplotlib.pyplot as plt

USERNAME = "muralimanas30"
REPO = "DSA-LEETCODE"
API_URL = f"https://leetcode-stats-api.herokuapp.com/{USERNAME}"
RAW_PIE_URL = f"https://raw.githubusercontent.com/{USERNAME}/{REPO}/main/leetcode_stats.png"
VIEW_COUNTER = f"https://views-counter.vercel.app/badge?pageId={USERNAME}%2F{REPO}&leftColor=000000&rightColor=0adb3f&type=total&label=Viewers&style=none"
QUOTE_SVG = "https://readme-typing-svg.herokuapp.com?size=22&duration=4000&color=36BCF7&center=true&vCenter=true&width=700&lines=Code.+Debug.+Repeat.;Keep+learning;+keep+improving.;DSA+is+superpower.;Stay+consistent+win+big."

def fetch_stats():
    try:
        res = requests.get(API_URL, timeout=10)
        return res.json() if res.status_code == 200 else {}
    except:
        return {}

def progress_bar(solved, total=3000, length=30):
    done = int(length * solved / total)
    return "[" + "█"*done + "▒"*(length-done) + f"] {solved}/{total}"

def gen_pie(easy, medium, hard):
    plt.figure(figsize=(4,4))
    plt.pie([easy, medium, hard], labels=["Easy","Medium","Hard"], autopct="%1.1f%%", colors=["#4CAF50","#FFC107","#F44336"])
    plt.title("Problem Distribution")
    plt.savefig("leetcode_stats.png", bbox_inches="tight")
    plt.close()

def main():
    stats = fetch_stats()
    solved = stats.get("totalSolved",0)
    easy = stats.get("easySolved",0)
    medium = stats.get("mediumSolved",0)
    hard = stats.get("hardSolved",0)
    rank = stats.get("ranking","N/A")
    bar = progress_bar(solved)

    gen_pie(easy, medium, hard)

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    readme = f"""# 📘 DSA-LEETCODE Dashboard

<p align="center">
  ![{USERNAME}'s View Counter]({VIEW_COUNTER})
</p>

<p align="center">
  <img src="https://img.shields.io/badge/Solved-{solved}-blue?style=for-the-badge" />
  <img src="https://img.shields.io/badge/Language-Java%2017-orange?style=for-the-badge" />
  <img src="https://img.shields.io/badge/Platform-LeetCode-yellow?style=for-the-badge" />
  <img src="https://img.shields.io/badge/AutoUpdate-Daily-success?style=for-the-badge" />
</p>

---

##  LeetCode Stats

| Metric | Value |
|--------|-------|
| Total Solved | {solved} |
| Easy / Medium / Hard | {easy} / {medium} / {hard} |
| Global Rank | {rank} |




{bar}



<p align="center">
  <img src="{RAW_PIE_URL}" alt="LeetCode Distribution" width="300"/>
</p>

---

##  Trends

<p align="center">
  <img src="https://streak-stats.demolab.com/?user={USERNAME}&theme=tokyonight&hide_border=true" alt="Streak" />
</p>
<p align="center">
  <img src="https://github-readme-activity-graph.vercel.app/graph?username={USERNAME}&theme=tokyo-night&hide_border=true" alt="Activity Graph" />
</p>

---

##  Dev Quote

<p align="center">
  <img src="{QUOTE_SVG}" alt="Typing Quote" />
</p>

---

*Generated by GitHub Workflows on {now}*
"""

    with open("README.md","w",encoding="utf-8") as f:
        f.write(readme)

if __name__ == "__main__":
    main()
