import requests
import datetime
import matplotlib.pyplot as plt

USERNAME = "muralimanas30"
REPO = "DSA-LEETCODE"

# ✅ Visitor counter
VIEW_BADGE = f"https://views-counter.vercel.app/badge?pageId=https://github.com/{USERNAME}/{REPO}&leftColor=000000&rightColor=0adb3f&type=total&label=Viewers&style=none"

# ✅ LeetCode API
url = f"https://leetcode-stats-api.herokuapp.com/{USERNAME}"
resp = requests.get(url).json()

solved = resp.get("totalSolved", 0)
easy = resp.get("easySolved", 0)
medium = resp.get("mediumSolved", 0)
hard = resp.get("hardSolved", 0)
rank = resp.get("ranking", "N/A")

# ✅ Pie chart
labels = ["Easy", "Medium", "Hard"]
sizes = [easy, medium, hard]
colors = ["#00c853", "#ffab00", "#d50000"]

plt.figure(figsize=(4, 4))
plt.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=140, colors=colors)
plt.axis("equal")
plt.savefig("leetcode_pie.png")

PIE_URL = "leetcode_pie.png"

# ✅ Fancy animated card
FANCY_CARD_URL = (
    "https://stats.maximjsx.com/api?"
    f"username={USERNAME}"
    "&theme=forest_winter"
    "&dark_bg=5"
    "&border_radius=10"
    "&show_icons=true"
    "&title=✨%20DSA%20Progress%20✨"
    "&description=LeetCode%20+%20GitHub%20stats%20with%20animated%20background"
    "&footer=Keep%20coding%20🔥"
)

# ✅ Fancy repo highlight card
FANCY_REPO_CARD = (
    f"https://stats.maximjsx.com/api/pin/?username={USERNAME}&repo={REPO}&theme=beach&dark_bg=6&show_icons=true"
)

# ✅ LeetCode ASCII bar
bar = f"[Easy: {'█'* (easy//10)}] [Medium: {'█'* (medium//10)}] [Hard: {'█'* (hard//10)}]"

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ✅ README content
readme = f"""# 📘 {REPO} Dashboard

<p align="center">
  <img src="{VIEW_BADGE}" alt="Viewers Counter" />
</p>

---

## ✨ Fancy GitHub Stats

<p align="center">
  <img src="{FANCY_CARD_URL}" alt="Fancy Animated Stats" />
</p>

---

## 📂 Repository Highlight

<p align="center">
  <a href="https://github.com/{USERNAME}/{REPO}">
    <img src="{FANCY_REPO_CARD}" alt="Repo Card" />
  </a>
</p>

---

## 📊 LeetCode Overview

- **Solved**: {solved} (Easy {easy}, Medium {medium}, Hard {hard})  
- **Global Rank**: {rank}  


{bar}

<p align="center">
  <img src="{PIE_URL}" alt="Difficulty Distribution" width="300"/>
</p>

---

## 🔥 Activity & Streaks

<p align="center">
  <img src="https://streak-stats.demolab.com/?user={USERNAME}&theme=tokyonight&hide_border=true" alt="Streak" />
</p>
<p align="center">
  <img src="https://github-readme-activity-graph.vercel.app/graph?username={USERNAME}&theme=tokyo-night&hide_border=true" alt="Activity Graph" />
</p>

---

## 💡 Dev Thoughts

<p align="center">
  <img src="https://readme-typing-svg.herokuapp.com?size=22&duration=4000&color=36BCF7&center=true&width=700&lines=Code.+Debug.+Repeat.;Keep+learning;+keep+improving.;DSA+is+superpower.;Consistency+beats+results." alt="Typing Quote" />
</p>

---

<p align="center">
  <sup>Generated by GitHub Workflows on {now}</sup>
</p>
"""

with open("README.md", "w") as f:
    f.write(readme)
