name: Update README Dashboard

on:
  schedule:
    - cron: "30 1 * * *"   # every day at 7 AM IST (1:30 UTC)
  workflow_dispatch:        # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Generate README Dashboard
        run: python3 .github/workflows/generate_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README dashboard" || echo "No changes to commit"
          git push
